# Generated by Django 3.1.1 on 2020-09-19 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id_boleta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cli', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, null=True)),
                ('password', models.CharField(max_length=30, null=True)),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('apellido', models.CharField(max_length=50, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('direccion', models.CharField(max_length=30, null=True)),
                ('rut', models.CharField(max_length=30, null=True)),
                ('telefono', models.IntegerField(verbose_name=12)),
                ('email', models.CharField(max_length=100, null=True)),
                ('id_boleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.boleta')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, null=True)),
                ('password', models.CharField(max_length=30, null=True)),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('apellido', models.CharField(max_length=50, null=True)),
                ('direccion', models.CharField(max_length=30, null=True)),
                ('rut', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('id_cli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('estado_recep', models.CharField(max_length=30, null=True)),
                ('id_cli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.cliente')),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, null=True)),
                ('precio', models.IntegerField(verbose_name=8)),
                ('stock', models.IntegerField(verbose_name=10)),
                ('disponibilidad', models.BooleanField(default=True)),
                ('familia', models.CharField(max_length=30, null=True)),
                ('fecha_ven', models.DateField(blank=True, null=True)),
                ('descripcion', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Emp',
            fields=[
                ('id_cargo', models.AutoField(primary_key=True, serialize=False)),
                ('cargo', models.CharField(max_length=30, null=True)),
                ('id_boleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.boleta')),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.empleado')),
                ('id_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.factura')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_prove', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, null=True)),
                ('rut_empresa', models.CharField(max_length=30, null=True)),
                ('rubro', models.CharField(max_length=30, null=True)),
                ('id_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.factura')),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.pedido')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.producto')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.producto'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='id_prove',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.proveedor'),
        ),
        migrations.AddField(
            model_name='factura',
            name='id_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.pedido'),
        ),
        migrations.AddField(
            model_name='factura',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.producto'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='id_cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.tipo_emp'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='id_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.pedido'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.factura'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.pedido'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.producto'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='id_cli',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.cliente'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='id_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.pedido'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.producto'),
        ),
    ]
