# Generated by Django 3.1.2 on 2020-10-05 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_producto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenproducto',
            name='orden',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.orden'),
        ),
        migrations.AlterField(
            model_name='ordenproducto',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.producto'),
        ),
    ]
